version: '2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    ports:
      - "27017:27017"
    volumes:
      - './database:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local
